from pathlib import Path

ROOT = Path('.')

def replace_once(text, old, new, label):
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected 1 occurrence, got {count}')
    return text.replace(old, new, 1)

# index.html
path = ROOT / 'index.html'
text = path.read_text()
text = replace_once(text, '''          <label class="uw-habit-icon-field" title="그룹"><span aria-hidden="true">◉</span><select id="habitPageGroup" aria-label="습관 그룹"></select></label>\n          <label class="uw-habit-duration-field"><span>길이</span><select id="habitPageDuration" aria-label="습관 길이"><option value="30">30분</option><option value="60">1시간</option><option value="90">1시간 30분</option><option value="120">2시간</option></select></label>''', '''          <label class="uw-habit-icon-field" title="그룹"><span aria-hidden="true">◉</span><select id="habitPageGroup" aria-label="습관 그룹"></select></label>\n          <label class="uw-habit-range-field"><span>시작</span><input id="habitPageStartDate" type="date" aria-label="습관 시작일" /></label>\n          <label class="uw-habit-range-field"><span>종료</span><input id="habitPageEndDate" type="date" aria-label="습관 종료일" /></label>\n          <label class="uw-habit-duration-field"><span>길이</span><select id="habitPageDuration" aria-label="습관 길이"><option value="30">30분</option><option value="60">1시간</option><option value="90">1시간 30분</option><option value="120">2시간</option></select></label>''', 'habit add date fields')
text = text.replace('css/unified-workspace.css?v=28', 'css/unified-workspace.css?v=29', 1)
text = text.replace('js/unified-workspace.js?v=29', 'js/unified-workspace.js?v=30', 1)
path.write_text(text)

# unified-workspace.js
path = ROOT / 'js/unified-workspace.js'
text = path.read_text()
text = replace_once(text, '''function habitOverride(source,date,id,create=false){if(!source||!date||!id)return null;if(create){source.habitOverrides||={};source.habitOverrides[date]||={};source.habitOverrides[date][id]||={}}return source.habitOverrides?.[date]?.[id]||null}\n''', '''function habitActiveOn(habit,date){if(!habit||!date)return false;if(habit.startDate&&date<habit.startDate)return false;if(habit.endDate&&date>habit.endDate)return false;return true}\nfunction habitOverride(source,date,id,create=false){if(!source||!date||!id)return null;if(create){source.habitOverrides||={};source.habitOverrides[date]||={};source.habitOverrides[date][id]||={}}return source.habitOverrides?.[date]?.[id]||null}\n''', 'habit active helper')
text = replace_once(text, '''  const habits=state.habitTemplates.flatMap(habit=>{const override=habitOverride(state,k,habit.id)||{};if(override.hidden)return[];const start=Object.prototype.hasOwnProperty.call(override,"startMinute")?override.startMinute:habit.startMinute;''', '''  const habits=state.habitTemplates.flatMap(habit=>{if(!habitActiveOn(habit,k))return[];const override=habitOverride(state,k,habit.id)||{};if(override.hidden)return[];const start=Object.prototype.hasOwnProperty.call(override,"startMinute")?override.startMinute:habit.startMinute;''', 'daily habit active range')
text = replace_once(text, '''  const byGroup=state.eventGroups.map(group=>({group,items:ordered.filter(h=>(h.groupId||state.eventGroups[0].id)===group.id)})).filter(x=>x.items.length);''', '''  const byGroup=state.eventGroups.map(group=>({group,items:ordered.filter(h=>(h.groupId||state.eventGroups[0].id)===group.id&&days.some(day=>habitActiveOn(h,key(day))))})).filter(x=>x.items.length);''', 'habit week group active range')
text = replace_once(text, '''${days.map(day=>{const date=key(day),done=!!state.habitDays[date]?.[h.id];return`<button class="uw-habit-day-check${done?" checked":""}" data-uw-habit-check="${h.id}" data-date="${date}" type="button" aria-label="${dayLabel(day)} ${done?"완료 취소":"완료"}">${done?"✓":""}</button>`}).join("")}''', '''${days.map(day=>{const date=key(day),active=habitActiveOn(h,date),done=active&&!!state.habitDays[date]?.[h.id];if(!active)return`<span class="uw-habit-day-check inactive" aria-hidden="true"></span>`;return`<button class="uw-habit-day-check${done?" checked":""}" data-uw-habit-check="${h.id}" data-date="${date}" type="button" aria-label="${dayLabel(day)} ${done?"완료 취소":"완료"}">${done?"✓":""}</button>`}).join("")}''', 'habit inactive day cells')
text = replace_once(text, '''  form.innerHTML=`${withTime?`<input type="time" value="${old&&kind==="event"&&!old.allDay?timeOf(old.start):time!==null?`${pad(Math.floor(time/60))}:${pad(time%60)}`:""}" aria-label="시간">`:""}<input type="text" value="${esc(displayTitle||"")}" placeholder="${kind==="event"?"일정":kind==="habit"?"습관":"할일"} 입력" autocomplete="off">${canRepeat?recurrenceEditorMarkup(old,frequency):""}`;''', '''  form.innerHTML=`${withTime?`<input type="time" value="${old&&kind==="event"&&!old.allDay?timeOf(old.start):time!==null?`${pad(Math.floor(time/60))}:${pad(time%60)}`:""}" aria-label="시간">`:""}<input type="text" value="${esc(displayTitle||"")}" placeholder="${kind==="event"?"일정":kind==="habit"?"습관":"할일"} 입력" autocomplete="off">${old&&kind==="habit"?`<div class="uw-habit-range-inline" title="모든 습관에 적용되는 기간"><label><span>시작</span><input class="uw-habit-start-date" type="date" value="${esc(old.startDate||"")}" aria-label="습관 시작일"></label><label><span>종료</span><input class="uw-habit-end-date" type="date" value="${esc(old.endDate||"")}" aria-label="습관 종료일"></label></div>`:""}${canRepeat?recurrenceEditorMarkup(old,frequency):""}`;''', 'habit edit active range fields')
text = replace_once(text, '''    const habitEditDate=date||todayKey();\n    const existingHabitOverride=old&&kind==="habit"?habitOverride(state,habitEditDate,old.id):null;''', '''    const habitEditDate=date||todayKey();\n    const habitStartDate=$(".uw-habit-start-date",form)?.value||"";\n    const habitEndDate=$(".uw-habit-end-date",form)?.value||"";\n    if(old&&kind==="habit"&&habitStartDate&&habitEndDate&&habitEndDate<habitStartDate){const endInput=$(".uw-habit-end-date",form);endInput?.setCustomValidity("종료일은 시작일과 같거나 이후여야 해요.");endInput?.reportValidity();saving=false;return}\n    const existingHabitOverride=old&&kind==="habit"?habitOverride(state,habitEditDate,old.id):null;''', 'habit edit date validation')
text = replace_once(text, '''          if(habitScope==="day")habitOverride(current,editDate,target.id,true).title=value;\n          else{target.title=value;const override=habitOverride(current,editDate,target.id);if(override){delete override.title;cleanHabitOverride(current,editDate,target.id)}}\n          return''', '''          if(habitScope==="day")habitOverride(current,editDate,target.id,true).title=value;\n          else{target.title=value;if(habitStartDate)target.startDate=habitStartDate;else delete target.startDate;if(habitEndDate)target.endDate=habitEndDate;else delete target.endDate;const override=habitOverride(current,editDate,target.id);if(override){delete override.title;cleanHabitOverride(current,editDate,target.id)}}\n          return''', 'habit edit save range')
text = replace_once(text, '''      }else if(kind==="habit"){\n        current.habitTemplates.push({id:uid(),title:value,groupId:defaultGroup})\n      }else{''', '''      }else if(kind==="habit"){\n        current.habitTemplates.push({id:uid(),title:value,groupId:defaultGroup,startDate:date||todayKey()})\n      }else{''', 'inline habit create start date')
old_wire = '''function wireHabitForm(){const form=$("#habitPageForm");if(!form||form.dataset.uwBound)return;form.dataset.uwBound="1";form.addEventListener("submit",async event=>{event.preventDefault();const title=$("#habitPageTitle")?.value.trim(),time=$("#habitPageTime")?.value||"",duration=Math.max(SLOT,+$("#habitPageDuration")?.value||SLOT),groupId=$("#habitPageGroup")?.value||state?.eventGroups?.[0]?.id||"default",button=form.querySelector('button[type="submit"]');if(!title)return;const original=button.dataset.defaultLabel||button.textContent;button.dataset.defaultLabel=original;button.disabled=true;button.textContent="추가 중…";try{await write(current=>{const habit={id:uid(),title,duration,groupId};if(time){const[hour,minute]=time.split(":").map(Number);habit.startMinute=hour*60+minute}current.habitTemplates.push(habit);const today=todayKey();current.habitDays[today]||={};current.habitDays[today][habit.id]=false});form.reset();$("#habitPageGroup").value=groupId}catch(error){console.error("습관 추가 실패",error);button.textContent="다시 시도"}finally{button.disabled=false;if(button.textContent!=="다시 시도")button.textContent=original}})}'''
new_wire = '''function wireHabitForm(){const form=$("#habitPageForm");if(!form||form.dataset.uwBound)return;form.dataset.uwBound="1";const startInput=$("#habitPageStartDate"),endInput=$("#habitPageEndDate");if(startInput&&!startInput.value)startInput.value=todayKey();endInput?.addEventListener("input",()=>endInput.setCustomValidity(""));form.addEventListener("submit",async event=>{event.preventDefault();const title=$("#habitPageTitle")?.value.trim(),time=$("#habitPageTime")?.value||"",duration=Math.max(SLOT,+$("#habitPageDuration")?.value||SLOT),groupId=$("#habitPageGroup")?.value||state?.eventGroups?.[0]?.id||"default",startDate=startInput?.value||todayKey(),endDate=endInput?.value||"",button=form.querySelector('button[type="submit"]');if(!title)return;if(endDate&&endDate<startDate){endInput?.setCustomValidity("종료일은 시작일과 같거나 이후여야 해요.");endInput?.reportValidity();return}const original=button.dataset.defaultLabel||button.textContent;button.dataset.defaultLabel=original;button.disabled=true;button.textContent="추가 중…";try{await write(current=>{const habit={id:uid(),title,duration,groupId,startDate};if(endDate)habit.endDate=endDate;if(time){const[hour,minute]=time.split(":").map(Number);habit.startMinute=hour*60+minute}current.habitTemplates.push(habit)});form.reset();$("#habitPageGroup").value=groupId;if(startInput)startInput.value=todayKey();if(endInput)endInput.value=""}catch(error){console.error("습관 추가 실패",error);button.textContent="다시 시도"}finally{button.disabled=false;if(button.textContent!=="다시 시도")button.textContent=original}})}'''
text = replace_once(text, old_wire, new_wire, 'habit add form active range')
path.write_text(text)

# css
path = ROOT / 'css/unified-workspace.css'
text = path.read_text()
text += '''\n/* Habit active range */\n.uw-habit-range-field{display:inline-flex;align-items:center;gap:5px;min-width:0;color:var(--muted);font-size:10px;white-space:nowrap}.uw-habit-range-field input{width:116px;height:32px;padding:4px 6px;border:1px solid var(--line);border-radius:7px;background:#fff;color:var(--text);font:inherit;font-size:10px}.uw-habit-day-check.inactive{border-style:dashed;border-color:color-mix(in srgb,var(--line) 75%,transparent);background:var(--panel-soft);opacity:.42}.uw-habit-range-inline{display:inline-flex;align-items:center;gap:4px}.uw-habit-range-inline label{display:inline-flex;align-items:center;gap:3px;color:var(--muted);font-size:9px;white-space:nowrap}.uw-habit-range-inline input[type=date]{width:112px;height:26px;padding:2px 4px;border:1px solid var(--line);border-radius:6px;background:#fff;color:var(--text);font-size:9px}.uw-inline-form:has(.uw-habit-range-inline){flex-wrap:wrap}.uw-inline-form:has(.uw-habit-range-inline)>input[type=text]{min-width:160px}@media(max-width:760px){.uw-habit-range-field{flex:1 1 145px}.uw-habit-range-field input{width:100%;min-width:0}.uw-habit-range-inline{width:100%;display:grid;grid-template-columns:1fr 1fr}.uw-habit-range-inline label{display:grid;grid-template-columns:auto 1fr}.uw-habit-range-inline input[type=date]{width:100%;height:34px;font-size:12px}}\n'''
path.write_text(text)

print('patched habit active range')
