from pathlib import Path

ROOT = Path('.')

def replace_once(text, old, new, label):
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected 1 occurrence, got {count}')
    return text.replace(old, new, 1)

# index.html
path = ROOT / 'index.html'
text = path.read_text()
text = replace_once(text, '''          <button data-work-kind="goal" data-work-status="long" type="button">장기 목표</button>\n          <button data-work-kind="goal" data-work-status="done" type="button">달성</button>''', '''          <button data-work-kind="goal" data-work-status="long" type="button">장기 목표</button>\n          <button data-work-kind="goal" data-work-status="done" type="button">달성</button>\n          <button data-work-kind="goal" data-work-status="closed" type="button">종료</button>''', 'goal closed tab')
text = replace_once(text, '''      <div class="field"><label>마감기한</label><input id="projectDeadline" type="date" /></div>\n      <section class="uw-project-plan-editor" id="projectPlanEditor" hidden>''', '''      <div class="field"><label>마감기한</label><input id="projectDeadline" type="date" /></div>\n      <section class="uw-goal-projects-editor" id="goalProjectsEditor" hidden>\n        <div class="uw-goal-projects-head"><strong>연결된 프로젝트</strong><small id="goalProjectCount"></small></div>\n        <div class="uw-goal-project-list" id="goalProjectList"></div>\n        <div class="uw-goal-project-add">\n          <input id="goalProjectNewTitle" type="text" maxlength="120" autocomplete="off" placeholder="새 프로젝트" aria-label="새 프로젝트" />\n          <button id="goalProjectAddBtn" type="button">＋ 추가</button>\n        </div>\n      </section>\n      <section class="uw-project-plan-editor" id="projectPlanEditor" hidden>''', 'goal linked projects editor')
text = text.replace('css/unified-workspace.css?v=27', 'css/unified-workspace.css?v=28', 1)
text = text.replace('js/work-management.js?v=10', 'js/work-management.js?v=11', 1)
text = text.replace('js/work-status-inline-add.js?v=4', 'js/work-status-inline-add.js?v=5', 1)
path.write_text(text)

# work-management.js
path = ROOT / 'js/work-management.js'
text = path.read_text()
text = replace_once(text, '''const goalDefs = [\n  { id: "short", label: "단기 목표", color: "#8fa9c4" },\n  { id: "long", label: "장기 목표", color: "#88b49a" },\n  { id: "done", label: "달성", color: "#a69ab8" },\n];''', '''const goalDefs = [\n  { id: "short", label: "단기 목표", color: "#8fa9c4" },\n  { id: "long", label: "장기 목표", color: "#88b49a" },\n  { id: "done", label: "달성", color: "#a69ab8" },\n  { id: "closed", label: "종료", color: "#b89a91" },\n];''', 'goal defs closed')
text = replace_once(text, '''    if (item.status === "완료") item.status = "done";\n    if (item.kind === "goal") {\n      item.status = item.status === "done" ? "done" : "doing";\n      if (!["short", "long"].includes(item.goalTerm)) item.goalTerm = "short";\n    } else if (!statusDefs.some((status) => status.id === item.status)) {''', '''    if (item.status === "완료") item.status = "done";\n    if (item.status === "종료") item.status = "closed";\n    if (item.kind === "goal") {\n      item.status = item.status === "done" ? "done" : item.status === "closed" ? "closed" : "doing";\n      if (!["short", "long"].includes(item.goalTerm)) item.goalTerm = "short";\n    } else if (!statusDefs.some((status) => status.id === item.status)) {''', 'goal migration closed')
text = replace_once(text, '''    if (item.status === "done" && !item.completedAt) item.completedAt = new Date().toISOString();\n    delete item.progress;''', '''    if (item.status === "done" && !item.completedAt) item.completedAt = new Date().toISOString();\n    if (item.kind === "goal" && item.status === "closed" && !item.closedAt) item.closedAt = new Date().toISOString();\n    delete item.progress;''', 'goal closed date migration')
text = replace_once(text, '''function dateMeta(item) {\n  const parts = [];\n  if (item.startDate) parts.push(`시작 ${item.startDate}`);\n  if (item.deadline) parts.push(`마감 ${item.deadline}`);\n  if (item.completedAt) parts.push(`${item.kind === "goal" ? "달성" : "완료"} ${String(item.completedAt).slice(0, 10)}`);\n  return parts.join(" · ") || "날짜 없음";\n}''', '''function dateMeta(item) {\n  const parts = [];\n  if (item.startDate) parts.push(`시작 ${item.startDate}`);\n  if (item.deadline) parts.push(`마감 ${item.deadline}`);\n  if (item.kind === "goal") {\n    if (item.status === "done" && item.completedAt) parts.push(`달성 ${String(item.completedAt).slice(0, 10)}`);\n    if (item.status === "closed" && item.closedAt) parts.push(`종료 ${String(item.closedAt).slice(0, 10)}`);\n  } else if (item.completedAt) {\n    parts.push(`완료 ${String(item.completedAt).slice(0, 10)}`);\n  }\n  return parts.join(" · ") || "날짜 없음";\n}''', 'goal date meta closed')
text = replace_once(text, '''    const matchesGoalSection = (item, section) => section === "done" ? item.status === "done" : item.status !== "done" && item.goalTerm === section;''', '''    const matchesGoalSection = (item, section) => {\n      if (section === "done") return item.status === "done";\n      if (section === "closed") return item.status === "closed";\n      return item.status === "doing" && item.goalTerm === section;\n    };''', 'goal section matcher')
text = replace_once(text, '''function fillDialogOptions() {\n  $("#projectGroup").innerHTML = state.eventGroups.map((group) => `<option value="${group.id}">${esc(group.name)}</option>`).join("");\n  const goalSelect = $("#projectGoal");\n  if (goalSelect) goalSelect.innerHTML = '<option value="">연결 안 함</option>' + state.projects.filter((item) => item.kind === "goal").map((goal) => `<option value="${goal.id}">${esc(goal.title)}</option>`).join("");\n}\n\nfunction openDialog(kind, item = null) {''', '''function fillDialogOptions() {\n  $("#projectGroup").innerHTML = state.eventGroups.map((group) => `<option value="${group.id}">${esc(group.name)}</option>`).join("");\n  const goalSelect = $("#projectGoal");\n  if (goalSelect) goalSelect.innerHTML = '<option value="">연결 안 함</option>' + state.projects.filter((item) => item.kind === "goal").map((goal) => `<option value="${goal.id}">${esc(goal.title)}</option>`).join("");\n}\n\nfunction renderGoalProjects(goalId) {\n  const editor = $("#goalProjectsEditor");\n  const list = $("#goalProjectList");\n  const count = $("#goalProjectCount");\n  if (!editor || !list) return;\n  const projects = goalId ? sorted(state.projects.filter((item) => item.kind === "project" && item.goalId === goalId)) : [];\n  editor.hidden = !goalId;\n  if (!goalId) {\n    list.innerHTML = "";\n    if (count) count.textContent = "";\n    return;\n  }\n  if (count) count.textContent = `${projects.length}개`;\n  list.innerHTML = projects.length ? projects.map((project) => `<div class="uw-goal-project-row" style="--uw-group:${groupOf(project).color}"><span></span><strong>${esc(project.title)}</strong><small>${esc(statusDefs.find((entry) => entry.id === project.status)?.label || "시작 전")}</small></div>`).join("") : '<div class="uw-goal-project-empty">아직 연결된 프로젝트가 없어요.</div>';\n}\n\nfunction openDialog(kind, item = null) {''', 'render linked projects')
text = replace_once(text, '''  if (kind === "goal") {\n    statusSelect.innerHTML = '<option value="doing">진행 중</option><option value="done">달성</option>';\n    statusSelect.value = item?.status === "done" ? "done" : "doing";''', '''  if (kind === "goal") {\n    statusSelect.innerHTML = '<option value="doing">진행 중</option><option value="done">달성</option><option value="closed">종료</option>';\n    statusSelect.value = item?.status === "done" ? "done" : item?.status === "closed" ? "closed" : "doing";''', 'goal status options')
text = replace_once(text, '''  const goalField = $("#projectGoalField");\n  const goalSelect = $("#projectGoal");\n  if (goalField) goalField.hidden = kind !== "project";\n  if (goalSelect) goalSelect.value = kind === "project" ? (item?.goalId || "") : "";''', '''  const goalField = $("#projectGoalField");\n  const goalSelect = $("#projectGoal");\n  if (goalField) {\n    goalField.hidden = kind !== "project";\n    goalField.style.display = kind === "project" ? "" : "none";\n  }\n  if (goalSelect) goalSelect.value = kind === "project" ? (item?.goalId || "") : "";\n  renderGoalProjects(kind === "goal" ? (item?.id || "") : "");''', 'goal parent visibility and project list')
text = replace_once(text, '''    if (item.kind === "goal") {\n      if (!goalDefs.some((entry) => entry.id === status)) return;\n      if (status === "done") {\n        item.status = "done";\n        item.completedAt ||= new Date().toISOString();\n      } else {\n        item.goalTerm = status;\n        item.status = "doing";\n        item.completedAt = null;\n      }\n      return;\n    }''', '''    if (item.kind === "goal") {\n      if (!goalDefs.some((entry) => entry.id === status)) return;\n      if (status === "done") {\n        item.status = "done";\n        item.completedAt ||= new Date().toISOString();\n        item.closedAt = null;\n      } else if (status === "closed") {\n        item.status = "closed";\n        item.closedAt ||= new Date().toISOString();\n        item.completedAt = null;\n      } else {\n        item.goalTerm = status;\n        item.status = "doing";\n        item.completedAt = null;\n        item.closedAt = null;\n      }\n      return;\n    }''', 'goal drag closed')
text = replace_once(text, '''        item.goalTerm = "short";\n        item.status = item.status === "done" ? "done" : "doing";''', '''        item.goalTerm = "short";\n        item.status = item.status === "done" ? "done" : "doing";\n        item.closedAt = null;''', 'convert goal cleanup')
text = replace_once(text, '''        delete item.goalId;\n        delete item.goalTerm;\n        if (!["before", "doing", "done", "stopped"].includes(item.status)) item.status = "before";''', '''        delete item.goalId;\n        delete item.goalTerm;\n        delete item.closedAt;\n        if (!["before", "doing", "done", "stopped"].includes(item.status)) item.status = "before";''', 'convert project cleanup')
text = replace_once(text, '''      item.title = title;\n      item.kind = kind;\n      item.status = kind === "goal" ? ($("#projectStatus").value === "done" ? "done" : "doing") : $("#projectStatus").value;''', '''      item.title = title;\n      item.kind = kind;\n      const selectedStatus = $("#projectStatus").value;\n      item.status = kind === "goal" ? (selectedStatus === "done" ? "done" : selectedStatus === "closed" ? "closed" : "doing") : selectedStatus;''', 'goal submit closed status')
text = replace_once(text, '''      if (item.status === "done") item.completedAt ||= new Date().toISOString();\n      else item.completedAt = null;''', '''      if (item.status === "done") {\n        item.completedAt ||= new Date().toISOString();\n        item.closedAt = null;\n      } else if (kind === "goal" && item.status === "closed") {\n        item.closedAt ||= new Date().toISOString();\n        item.completedAt = null;\n      } else {\n        item.completedAt = null;\n        if (kind === "goal") item.closedAt = null;\n      }''', 'goal submit dates')
text = replace_once(text, '''  $("#cancelProjectBtn")?.addEventListener("click", () => $("#projectDialog")?.close());\n  $("#convertProjectBtn")?.addEventListener("click", async (event) => {''', '''  $("#cancelProjectBtn")?.addEventListener("click", () => $("#projectDialog")?.close());\n  $("#goalProjectAddBtn")?.addEventListener("click", async () => {\n    const goalId = $("#projectKind")?.value === "goal" ? $("#projectId")?.value : "";\n    const input = $("#goalProjectNewTitle");\n    const title = input?.value.trim() || "";\n    if (!goalId || !title) return;\n    const button = $("#goalProjectAddBtn");\n    if (button) button.disabled = true;\n    try {\n      await writeState((current) => {\n        const goal = current.projects.find((item) => item.id === goalId && item.kind === "goal");\n        if (!goal) return;\n        current.projects.push({\n          id: uid(),\n          kind: "project",\n          title,\n          status: "before",\n          groupId: $("#projectGroup")?.value || goal.groupId || current.eventGroups[0]?.id || "default",\n          goalId,\n          startDate: todayKey(),\n          deadline: "",\n          createdAt: new Date().toISOString(),\n        });\n      });\n      if (input) input.value = "";\n      renderGoalProjects(goalId);\n      input?.focus({ preventScroll: true });\n    } finally {\n      if (button) button.disabled = false;\n    }\n  });\n  $("#goalProjectNewTitle")?.addEventListener("keydown", (event) => {\n    if (event.key !== "Enter") return;\n    event.preventDefault();\n    event.stopPropagation();\n    $("#goalProjectAddBtn")?.click();\n  });\n  $("#convertProjectBtn")?.addEventListener("click", async (event) => {''', 'goal project quick add listeners')
path.write_text(text)

# work-status-inline-add.js
path = ROOT / 'js/work-status-inline-add.js'
text = path.read_text()
text = replace_once(text, '''    status: kind === "goal" ? (goalSection === "done" ? "done" : "doing") : status,''', '''    status: kind === "goal" ? (goalSection === "done" ? "done" : goalSection === "closed" ? "closed" : "doing") : status,''', 'quick add goal closed status')
text = replace_once(text, '''  if (kind === "goal") item.goalTerm = goalSection === "long" ? "long" : "short";\n  if (item.status === "done") item.completedAt = new Date().toISOString();''', '''  if (kind === "goal") item.goalTerm = goalSection === "long" ? "long" : "short";\n  if (item.status === "done") item.completedAt = new Date().toISOString();\n  if (item.status === "closed") item.closedAt = new Date().toISOString();''', 'quick add goal closed date')
path.write_text(text)

# unified-workspace.css
path = ROOT / 'css/unified-workspace.css'
text = path.read_text()
text = text.replace('.uw-goal-status-board{grid-template-columns:repeat(3,minmax(0,1fr))!important}', '.uw-goal-status-board{grid-template-columns:repeat(4,minmax(0,1fr))!important}', 1)
text = text.replace('@media(max-width:900px){.uw-goal-status-board{grid-template-columns:repeat(3,minmax(230px,76vw))!important}}', '@media(max-width:900px){.uw-goal-status-board{grid-template-columns:repeat(4,minmax(230px,76vw))!important}}', 1)
marker = '/* Goal linked projects editor */'
if marker not in text:
    text += '''\n\n/* Goal linked projects editor */\n#projectGoalField[hidden]{display:none!important}\n.uw-goal-projects-editor{display:grid;gap:8px;margin-top:12px;padding-top:12px;border-top:1px solid var(--line)}\n.uw-goal-projects-editor[hidden]{display:none!important}\n.uw-goal-projects-head{display:flex;align-items:center;justify-content:space-between;gap:8px}\n.uw-goal-projects-head strong{font-size:12px}.uw-goal-projects-head small{color:var(--muted);font-size:9px}\n.uw-goal-project-list{display:grid;gap:5px;max-height:210px;overflow-y:auto;overscroll-behavior:contain}\n.uw-goal-project-row{display:grid;grid-template-columns:8px minmax(0,1fr) auto;align-items:center;gap:7px;min-height:34px;padding:6px 8px;border:1px solid var(--line);border-radius:9px;background:#fff}\n.uw-goal-project-row>span{width:7px;height:7px;border-radius:50%;background:var(--uw-group)}\n.uw-goal-project-row strong{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:10px}.uw-goal-project-row small{color:var(--muted);font-size:9px}\n.uw-goal-project-empty{padding:9px;border-radius:8px;background:var(--soft);color:var(--muted);font-size:10px}\n.uw-goal-project-add{display:flex;align-items:center;gap:6px;padding:7px;border-radius:9px;background:var(--soft)}\n.uw-goal-project-add input{min-width:0;flex:1;height:31px;padding:5px 7px;border:1px solid var(--line);border-radius:7px;background:#fff;font:inherit;font-size:10px;outline:0}.uw-goal-project-add input:focus{border-color:var(--accent)}\n.uw-goal-project-add button{min-height:31px;padding:4px 10px;border:0;border-radius:7px;background:var(--accent);color:#fff;font-size:10px;cursor:pointer}\n@media(max-width:700px){.uw-goal-projects-editor{margin-top:10px;padding-top:10px}.uw-goal-project-list{max-height:180px}.uw-goal-project-add input{height:34px;font-size:12px}}\n'''
path.write_text(text)
