from pathlib import Path

u_path = Path('js/unified-workspace.js')
c_path = Path('css/unified-workspace.css')
i_path = Path('index.html')

u = u_path.read_text(encoding='utf-8')
c = c_path.read_text(encoding='utf-8')
i = i_path.read_text(encoding='utf-8')

# Remove the dedicated planning handle; untimed task/habit rows remain planning-draggable.
old = '''function timeBlockV2ItemMarkup(entry,k,templates,assignment=null){\n  const kind=entry.kind,item=entry.item,done=itemDoneOn(kind,item,k),repeat=recurrenceLabel(item),occurrence=(kind==="task"||kind==="event")&&item._occurrenceSource?` data-occurrence-source="${item._occurrenceSource}"`:"",time=entry.timed?timeBlockV2MinuteText(entry.time):"",token=timeBlockV2EntryToken(entry,k),assignable=timeBlockV2Assignable(entry),planningClass=entry.timed?" fixed-anchor":assignable?" plan-draggable":"",planningAttrs=entry.timed?` data-time-block-anchor="${esc(token)}"`:assignable?` data-time-block-token="${esc(token)}"${assignment?` data-time-block-block-id="${esc(assignment.blockId)}" data-time-block-after-anchor="${esc(assignment.afterAnchor||TIME_BLOCK_START_ANCHOR)}" data-time-block-order="${Math.max(1,Number(assignment.order)||1)}"`:""}`:"",dragHandle=assignable?`<button class="uw-time-block-drag-handle" data-uw-time-block-drag data-token="${esc(token)}" type="button" aria-label="타임블럭 안에서 순서 이동" title="끌어서 순서 이동">⠿</button>`:"";\n  return`<div class="uw-item uw-${kind} uw-time-block-v2-item${entry.timed?" timed":" untimed"}${planningClass}${done?" done":""}" style="${groupStyle(item)}" data-uw-kind="${kind}" data-id="${item.id}" data-date="${k}"${occurrence}${planningAttrs} draggable="false">${dragHandle}${checkMarkup(kind,item,k)}<span class="uw-item-title">${esc(item.title)}</span>${repeat?`<span class="uw-repeat-badge">↻ ${repeat}</span>`:""}${time?`<span class="uw-item-time">${time}</span>`:""}<button class="uw-select-circle" type="button" aria-label="선택"></button></div>`\n}\n'''
new = '''function timeBlockV2ItemMarkup(entry,k,templates,assignment=null){\n  const kind=entry.kind,item=entry.item,done=itemDoneOn(kind,item,k),repeat=recurrenceLabel(item),occurrence=(kind==="task"||kind==="event")&&item._occurrenceSource?` data-occurrence-source="${item._occurrenceSource}"`:"",time=entry.timed?timeBlockV2MinuteText(entry.time):"",token=timeBlockV2EntryToken(entry,k),assignable=timeBlockV2Assignable(entry),planningClass=entry.timed?" fixed-anchor":assignable?" plan-draggable":"",planningAttrs=entry.timed?` data-time-block-anchor="${esc(token)}"`:assignable?` data-time-block-token="${esc(token)}"${assignment?` data-time-block-block-id="${esc(assignment.blockId)}" data-time-block-after-anchor="${esc(assignment.afterAnchor||TIME_BLOCK_START_ANCHOR)}" data-time-block-order="${Math.max(1,Number(assignment.order)||1)}"`:""}`:"";\n  return`<div class="uw-item uw-${kind} uw-time-block-v2-item${entry.timed?" timed":" untimed"}${planningClass}${done?" done":""}" style="${groupStyle(item)}" data-uw-kind="${kind}" data-id="${item.id}" data-date="${k}"${occurrence}${planningAttrs} draggable="false">${checkMarkup(kind,item,k)}<span class="uw-item-title">${esc(item.title)}</span>${repeat?`<span class="uw-repeat-badge">↻ ${repeat}</span>`:""}${time?`<span class="uw-item-time">${time}</span>`:""}<button class="uw-select-circle" type="button" aria-label="선택"></button></div>`\n}\n'''
if old not in u:
    raise SystemExit('timeBlockV2ItemMarkup stage5 version not found')
u = u.replace(old, new, 1)

# Remove the click guard that existed only for the dedicated drag handle.
u = u.replace('if(e.target.closest("[data-uw-time-block-drag]")){e.preventDefault();e.stopImmediatePropagation();return}', '', 1)

# Full-row pointerdown: any non-interactive point on an untimed planning row can start planning drag.
old = '''    const resizeHandle=e.target.closest("[data-uw-resize]");\n    const planHandle=e.target.closest("[data-uw-time-block-drag]");\n    const moveHandle=e.target.closest(".uw-move-handle");\n    const item=(resizeHandle||planHandle||moveHandle)?.closest(".uw-item")||e.target.closest(".uw-item");\n    let mode=null,source=null;\n    if(resizeHandle){mode="resize";source=resizeHandle}\n    else if(planHandle&&item?.classList.contains("uw-time-block-v2-item")){mode="time-block-plan";source=planHandle}\n    else if(moveHandle&&item?.classList.contains("selected")){mode="move";source=moveHandle}\n    else if(!coarse()&&item&&!item.classList.contains("uw-time-block-v2-item")&&e.target.closest(".uw-item-title,.uw-habit-title")){mode="move";source=e.target.closest(".uw-item-title,.uw-habit-title")}\n'''
new = '''    const resizeHandle=e.target.closest("[data-uw-resize]");\n    const moveHandle=e.target.closest(".uw-move-handle");\n    const item=(resizeHandle||moveHandle)?.closest(".uw-item")||e.target.closest(".uw-item");\n    const plannerRow=item?.classList.contains("uw-time-block-v2-item")&&item.classList.contains("plan-draggable")&&!e.target.closest("button,input,select,textarea,a,[contenteditable=true]");\n    let mode=null,source=null;\n    if(resizeHandle){mode="resize";source=resizeHandle}\n    else if(plannerRow){mode="time-block-plan";source=item}\n    else if(moveHandle&&item?.classList.contains("selected")){mode="move";source=moveHandle}\n    else if(!coarse()&&item&&!item.classList.contains("uw-time-block-v2-item")&&e.target.closest(".uw-item-title,.uw-habit-title")){mode="move";source=e.target.closest(".uw-item-title,.uw-habit-title")}\n'''
if old not in u:
    raise SystemExit('planner pointerdown block not found')
u = u.replace(old, new, 1)

# Token now comes from row metadata, not a removed handle.
u = u.replace('g.token=source.dataset.token||item.dataset.timeBlockToken||"";', 'g.token=item.dataset.timeBlockToken||"";', 1)

# On touch/coarse pointers, use the same deliberate long-press protection as other item movement.
u = u.replace('if(g.coarse&&mode!=="time-block-plan")g.timer=setTimeout(()=>activate(g),450);', 'if(g.coarse)g.timer=setTimeout(()=>activate(g),450);', 1)
old = '''    if(!g.active){\n      if(g.mode==="time-block-plan"){\n        if(distance>=3)activate(g);\n        if(!g.active)return\n      }else{\n        if(g.coarse&&distance>10){g.cancelled=true;clear(g);return}\n        if(!g.coarse&&distance>=6)activate(g);\n        if(!g.active)return\n      }\n    }\n'''
new = '''    if(!g.active){\n      if(g.coarse&&distance>10){g.cancelled=true;clear(g);return}\n      if(!g.coarse&&distance>=6)activate(g);\n      if(!g.active)return\n    }\n'''
if old not in u:
    raise SystemExit('planner activation block not found')
u = u.replace(old, new, 1)

# Replace stage5 handle CSS with row-drag affordance, preserving insertion indicators.
old_css = '''/* Time block V2 stage 5: direct planning drag */\n.uw-time-block-v2-list{position:relative}\n.uw-time-block-v2-item.fixed-anchor{cursor:default}\n.uw-time-block-v2-item.plan-draggable{cursor:default}\n.uw-time-block-drag-handle{display:inline-grid;place-items:center;width:24px;height:24px;flex:0 0 24px;padding:0;border:0;border-radius:7px;background:transparent;color:var(--muted);font:inherit;font-size:15px;line-height:1;cursor:grab;touch-action:none;user-select:none}\n.uw-time-block-drag-handle:hover,.uw-time-block-drag-handle:focus-visible{background:color-mix(in srgb,var(--accent) 12%,#fff);color:var(--accent-dark);outline:none}\n.uw-time-block-drag-handle:active{cursor:grabbing}\n.uw-time-block-v2-item.uw-time-block-drop-before::before,.uw-time-block-v2-item.uw-time-block-drop-after::after{content:"";position:absolute;right:5px;left:5px;z-index:12;height:2px;border-radius:99px;background:var(--accent);box-shadow:0 0 0 1px color-mix(in srgb,var(--accent) 12%,transparent);pointer-events:none}\n.uw-time-block-v2-item.uw-time-block-drop-before::before{top:-4px}\n.uw-time-block-v2-item.uw-time-block-drop-after::after{bottom:-4px}\n.uw-time-block-v2-list.uw-time-block-drop-bottom::after{content:"";display:block;height:2px;margin:3px 5px 1px;border-radius:99px;background:var(--accent);box-shadow:0 0 0 1px color-mix(in srgb,var(--accent) 12%,transparent);pointer-events:none}\n.uw-time-block-v2-list[data-uw-time-block-unassigned].uw-drop-target{outline:2px solid var(--accent)!important;outline-offset:-2px;border-radius:7px;background:color-mix(in srgb,var(--accent) 7%,transparent)!important}\n.uw-drag-ghost .uw-time-block-drag-handle{display:none!important}\n@media(hover:none),(pointer:coarse){.uw-time-block-drag-handle{width:32px;height:32px;flex-basis:32px;font-size:18px}.uw-time-block-v2-item.plan-draggable{min-height:42px}.uw-time-block-v2-item.uw-time-block-drop-before::before{top:-5px}.uw-time-block-v2-item.uw-time-block-drop-after::after{bottom:-5px}}'''
new_css = '''/* Time block V2 stage 5: full-row planning drag */\n.uw-time-block-v2-list{position:relative}\n.uw-time-block-v2-item.fixed-anchor{cursor:default}\n.uw-time-block-v2-item.plan-draggable{cursor:grab;user-select:none}\n.uw-time-block-v2-item.plan-draggable.uw-dragging,.uw-time-block-v2-item.plan-draggable.uw-drag-ready{cursor:grabbing}\n.uw-time-block-v2-item.plan-draggable button{cursor:pointer}\n.uw-time-block-v2-item.uw-time-block-drop-before::before,.uw-time-block-v2-item.uw-time-block-drop-after::after{content:"";position:absolute;right:5px;left:5px;z-index:12;height:2px;border-radius:99px;background:var(--accent);box-shadow:0 0 0 1px color-mix(in srgb,var(--accent) 12%,transparent);pointer-events:none}\n.uw-time-block-v2-item.uw-time-block-drop-before::before{top:-4px}\n.uw-time-block-v2-item.uw-time-block-drop-after::after{bottom:-4px}\n.uw-time-block-v2-list.uw-time-block-drop-bottom::after{content:"";display:block;height:2px;margin:3px 5px 1px;border-radius:99px;background:var(--accent);box-shadow:0 0 0 1px color-mix(in srgb,var(--accent) 12%,transparent);pointer-events:none}\n.uw-time-block-v2-list[data-uw-time-block-unassigned].uw-drop-target{outline:2px solid var(--accent)!important;outline-offset:-2px;border-radius:7px;background:color-mix(in srgb,var(--accent) 7%,transparent)!important}\n@media(hover:none),(pointer:coarse){.uw-time-block-v2-item.plan-draggable{min-height:42px;cursor:default}.uw-time-block-v2-item.uw-time-block-drop-before::before{top:-5px}.uw-time-block-v2-item.uw-time-block-drop-after::after{bottom:-5px}}'''
if old_css not in c:
    raise SystemExit('stage5 drag CSS not found')
c = c.replace(old_css, new_css, 1)

if './js/unified-workspace.js?v=43' not in i or './css/unified-workspace.css?v=36' not in i:
    raise SystemExit('unexpected cache versions')
i = i.replace('./js/unified-workspace.js?v=43', './js/unified-workspace.js?v=44', 1)
i = i.replace('./css/unified-workspace.css?v=36', './css/unified-workspace.css?v=37', 1)

u_path.write_text(u, encoding='utf-8')
c_path.write_text(c, encoding='utf-8')
i_path.write_text(i, encoding='utf-8')
